# SPDX-FileCopyrightText: 2021-2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = [
    ".gitignore",
    "CHANGELOG.md",
    "README.md",
    "tests/scripts/**",
]
precedence = "override"
SPDX-FileCopyrightText = "2021-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
