# SPDX-FileCopyrightText: 2021-2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

version = 1

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    "CHANGELOG.md",
    "README.md",
    "tests/scripts/**",
]
SPDX-FileCopyrightText = "2021-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
